export const BATCH_SIZE = 10;
export type GenerationMode = "transparent_png" | "regular_scene";

// One distinct buyer-use theme per day of the month. These are hypotheses
// informed by public Adobe Stock portfolio ordering, not verified sales data.
export const MONTHLY_CATEGORIES = [
  { day: 1, name: "Copy-space hospitality interiors", mode: "regular_scene", kind: "advertising", buyer: "hospitality marketers and interior publishers needing usable room scenes with copy space", seeds: ["sunlit boutique hotel lobby with a clear wall for campaign copy", "quiet cafe corner with an unbranded menu board and window light", "small hotel room staged for a travel booking campaign", "restaurant booth with warm lamps and uncluttered table", "modern coworking lounge with space for editorial headline", "spa reception with natural stone and towels", "independent bookstore reading corner with room for a seasonal message", "neighborhood bakery counter before opening", "minimal salon interior with product shelf and soft daylight", "conference venue lobby prepared before guests arrive"] },
  { day: 2, name: "Restaurant-ready food still life", mode: "regular_scene", kind: "advertising", buyer: "food publishers, restaurant menus, and packaged-food marketers seeking appetizing, clearly styled dishes", seeds: ["seared salmon with crisp skin and lemon herb garnish", "sliced roast vegetables arranged for a plant-forward menu", "handmade chocolate assortment with visible cacao texture", "fresh noodle bowl with steam and carefully arranged toppings", "rustic bread loaf cut to show its crumb", "grilled seasonal vegetables on a ceramic plate", "small bowl of citrus segments and peel on linen", "stack of savory lunch sandwiches cut cleanly in half", "berry tart with glossy fruit and pastry detail", "olive oil tasting plate with bread and herbs"] },
  { day: 3, name: "Authentic family and companion-animal moments", mode: "regular_scene", kind: "advertising", buyer: "family brands, pet-care marketers, and editorial publishers seeking warm candid lifestyle scenes", seeds: ["older dog resting beside a family reading on the floor", "parent fastening a toddler's raincoat before a walk", "siblings sharing a quiet craft activity at a kitchen table", "small dog waiting patiently beside a hiking backpack", "grandparent teaching a child to water balcony plants", "family preparing a simple weekend lunch together", "cat watching a person arrange fresh flowers", "child's hands building a cardboard toy with an adult", "rescue dog learning a calm leash routine in a garden", "multigenerational family looking through printed travel photos"] },
  { day: 4, name: "Botanical and culinary ingredient cutouts", mode: "transparent_png", kind: "asset", buyer: "food designers and wellness publishers needing clean, reusable botanical ingredient elements", seeds: ["single fresh neem leaf with accurate serrated edge", "small cluster of mint leaves with visible veins", "turmeric root with one cut face showing vivid interior", "rosemary sprig arranged as a compact ingredient element", "citrus slice with thin peel and a few leaves", "handful of green cardamom pods at mixed angles", "fresh curry leaf branch with separated leaflets", "small group of ripe berries with two detached leaves", "ginger root segments with natural branching", "single calendula flower with layered petals and green base"] },
  { day: 5, name: "Finance and business decision concepts", mode: "regular_scene", kind: "advertising", buyer: "financial services and business publishers needing clear metaphorical images without readable UI", seeds: ["small business owner reviewing cash flow papers at a sunlit desk", "abstract paper graph and calculator arranged for a budgeting article", "team comparing physical planning cards around a meeting table", "close view of hands sorting invoices beside a laptop with blank screen", "balanced stack of coins beside a growing seedling as a savings metaphor", "market analyst pointing at an unlabeled chart on glass", "entrepreneur reviewing delivery costs beside packed orders", "two colleagues discussing a printed forecast with no legible numbers", "secure contactless payment gesture at a neighborhood shop", "business succession discussion between two generations at a workshop"] },
  { day: 6, name: "Destination-specific travel and city stories", mode: "regular_scene", kind: "advertising", buyer: "tourism boards and travel publishers needing contextual destination imagery with editorial utility", seeds: ["spiral staircase viewed from below in a contemporary public building", "commuter train passing a low-rise city neighborhood at sunset", "quiet canal-side street with bicycles and local storefronts", "mountain valley viewed from a marked public trail overlook", "morning market lane with vendors preparing stalls before opening", "historic stone arcade with a single traveler seen from behind", "coastal ferry approaching a working harbor in soft haze", "urban rooftop garden above a dense skyline", "rain-wet tram tracks reflecting warm storefront lights", "public courtyard with a distinct local paving pattern and no logos"] },
  { day: 7, name: "Expressive pet portraits and care", mode: "regular_scene", kind: "advertising", buyer: "veterinary services, pet-care brands, and animal welfare publishers", seeds: ["close portrait of a senior mixed-breed dog with calm expression", "curious terrier watching a treat just outside the frame", "long-haired cat stretching beside a bright window", "hands gently brushing a rescue dog's coat", "wet dog shaking off after a safe beach walk", "sleeping puppy tucked on a plain washable blanket", "veterinarian examining a dog's paw in a calm clinic", "two cats sharing a sunlit resting spot", "dog wearing a simple reflective harness on an evening walk", "rabbit investigating fresh greens in a clean enclosure"] },
  { day: 8, name: "Botanical seamless pattern and surface design", mode: "regular_scene", kind: "artwork", buyer: "surface designers and stationery publishers looking for repeatable original botanical artwork", seeds: ["small citrus blossoms and paired leaves on a generous repeat", "stylized fern fronds alternating with seed pods", "abstract mangrove roots reduced to a two-color rhythm", "hand-drawn herb sprigs with varied scale and spacing", "simple wildflower heads connected by thin stems", "stylized tropical leaf silhouettes with open negative space", "pomegranate branches with small leaves and fruit", "repeating ginkgo leaves in an irregular diagonal flow", "pressed meadow stems translated into a flat repeat", "minimal mushroom caps and woodland leaves in a quiet palette"] },
  { day: 9, name: "Healthcare professionals in everyday practice", mode: "regular_scene", kind: "advertising", buyer: "healthcare organizations and patient-education publishers seeking respectful non-diagnostic imagery", seeds: ["nurse explaining a care plan to an older adult at eye level", "pharmacist arranging unbranded medicine boxes on a counter", "doctor reviewing a blank tablet screen in a bright clinic", "physical therapist guiding a safe seated mobility exercise", "care team discussing a patient chart with text turned away", "hands preparing a clean examination room between appointments", "community health worker listening to a client in a neutral office", "laboratory technician checking unlabeled sample tubes", "dentist showing a mirror to a relaxed patient before treatment", "caregiver helping an older adult organize a weekly pill case"] },
  { day: 10, name: "Regional ingredients and home cooking", mode: "regular_scene", kind: "advertising", buyer: "recipe publishers and food brands needing specific ingredient-led kitchen stories", seeds: ["fresh curry leaves and whole spices prepared for a home recipe", "rice noodles draining beside chopped herbs and lime", "roasted root vegetables cooling on a metal tray", "dumpling folding hands at a clean home kitchen counter", "mortar and pestle crushing herbs beside measured ingredients", "fresh mango slices with sticky rice served in a small ceramic dish", "vegetable broth ingredients arranged by preparation stage", "glass jar of overnight oats with fruit layers", "chili and garlic being chopped on a wooden board", "simple tea service with sliced citrus and dried leaves"] },
  { day: 11, name: "Nature textures and leafy copy space", mode: "regular_scene", kind: "advertising", buyer: "wellness, gardening, and environmental publishers seeking natural textures with flexible layout", seeds: ["backlit palm leaves framing a pale open sky", "macro view of rain beads along a waxy leaf edge", "layered fern shadows across a quiet garden wall", "young herb bed after watering with open soil foreground", "soft-focus orchard leaves around a single ripe fruit", "fine moss texture on shaded stone with negative space", "wind-shaped dune grasses against a bright coastal sky", "close view of seed heads in late afternoon light", "leaf canopy framing a narrow forest footpath", "water ripples reflecting a cluster of floating leaves"] },
  { day: 12, name: "Small-business product packaging scenes", mode: "regular_scene", kind: "advertising", buyer: "independent product brands needing adaptable packaging and storefront campaign imagery", seeds: ["unbranded refill pouch standing beside its reusable container", "amber glass skincare bottle beside a folded cotton towel", "kraft carton and paper tape arranged for a small online order", "ceramic candle jar with an unprinted paper label", "reusable drink bottle beside climbing gear on a bench", "small batch soap bars wrapped in plain paper and twine", "coffee beans in a clear jar beside a scoop and linen", "minimal product box on a textured shelf with copy space", "maker's hands packing a ceramic item with recycled paper", "unbranded glass jar with dried herbs and a blank label"] },
  { day: 13, name: "Playful circus-inspired children's rooms", mode: "regular_scene", kind: "advertising", buyer: "nursery publishers and family brands seeking imaginative but livable room decor", seeds: ["muted red and cream striped nursery canopy above an empty crib", "original carousel-animal print above a low wooden shelf", "small reading nook with a fabric big-top canopy and floor cushions", "circus-inspired arched alcove in a calm child's room", "wooden toy carousel on a low shelf beside linen storage", "soft scalloped valance and restrained fairground color palette", "playroom with hand-painted geometric tent stripes", "storybook animal bunting with no letters or familiar characters", "warm nursery corner with a vintage fairground color palette", "circus-themed wall mural using original abstract animal shapes"] },
  { day: 14, name: "Botanical wedding and event design elements", mode: "transparent_png", kind: "asset", buyer: "wedding stationery designers needing modular botanical ornaments without lettering", seeds: ["asymmetric olive branch and linen ribbon corner spray", "wildflower crescent with fine stems and generous open center", "citrus blossom cluster with two leaves and a small ribbon knot", "pressed fern ornament with a simple circular wax-seal form", "orchid and palm frond invitation-side decoration", "pomegranate branch forming one side of an open arch", "dried grass wreath with a deliberately open lower edge", "fig leaf pair with soft silk ribbon loop", "violet pansy cluster with tiny buds and no text", "cosmos flower bouquet tied with a narrow copper-colored ribbon"] },
  { day: 15, name: "Music, sound, and creative culture visuals", mode: "regular_scene", kind: "advertising", buyer: "music educators, event publishers, and creative campaigns needing original music-related imagery", seeds: ["abstract flowing staff lines with a small cluster of red notes", "headphones surrounded by paper-cut sound waves", "hands arranging blank vinyl sleeves before a listening session", "small rehearsal room with chairs and instruments before musicians arrive", "colorful percussion instruments arranged as a rhythmic still life", "abstract sound-wave sculpture made from layered paper", "music student annotating a score with no readable marks", "backstage microphone and cable under a single warm spotlight", "original geometric record-label-inspired artwork without lettering", "quiet piano keys with a reflected window and copy space"] },
  { day: 16, name: "Everyday urban mobility and public transit", mode: "regular_scene", kind: "advertising", buyer: "mobility services and city publishers needing grounded, inclusive transit imagery", seeds: ["hands holding a transit card near an unbranded station reader", "bicycle parked beside a secure city bike rack after rain", "commuters waiting in a bright station with faces indistinct", "wheelchair user approaching a step-free train platform", "bus shelter with a clean empty panel and evening reflections", "folding bicycle beside a compact apartment entry", "pedestrian crossing with tactile paving in soft morning light", "electric bus charging at a quiet depot", "city tram turning through a tree-lined street", "delivery rider checking a paper route map beside a bicycle"] },
  { day: 17, name: "Climate-smart gardens and food growing", mode: "transparent_png", kind: "asset", buyer: "sustainability educators and urban agriculture projects needing clear explanatory components", seeds: ["rain barrel diverter with simple realistic connectors", "drip irrigation emitter and short section of tubing", "permeable paving cross-section with visible aggregate layers", "modular green roof drainage tray with sedum plug", "small bioswale soil profile with roots and stone inlet", "reusable seedling tray with young vegetable starts", "solar shading louver assembly for a greenhouse roof", "compost sifter with mature compost in mesh basket", "raised garden bed corner connector made from recycled lumber", "greywater filter cartridge with clearly separated components"] },
  { day: 18, name: "Community arts and local maker events", mode: "regular_scene", kind: "advertising", buyer: "municipal arts programs and community organizations seeking participatory event illustrations", seeds: ["adult neighbors making a collaborative paper collage at a library", "local printmaking workshop with hands in action and faces distant", "artist arranging small prints at an outdoor neighborhood market", "volunteers painting an original abstract mural from behind", "community pottery class sharing a long worktable", "open studio visitors viewing work without readable signs", "artists setting up a compact weekend print fair", "multigenerational group preparing a community gallery wall", "hands binding a zine at a local maker workshop", "neighbors laying out handmade posters on a table before an event"] },
  { day: 19, name: "Cybersecurity and practical digital privacy", mode: "regular_scene", kind: "advertising", buyer: "technology companies and digital-literacy educators needing understandable non-branded cyber visuals", seeds: ["hands securing a laptop with a physical privacy shutter", "home router beside a paper checklist with no legible text", "small business owner reviewing device access at a clean desk", "abstract lock-shaped shadow across a network cable arrangement", "phone and security key on a neutral work surface", "employee closing unused laptop before leaving a shared office", "data backup drive beside neatly labeled blank storage boxes", "hands checking a generic security settings screen kept unreadable", "conceptual shield formed by overlapping translucent-free paper layers", "family placing devices in a charging station away from bedrooms"] },
  { day: 20, name: "Contemporary kitchen and home renovation", mode: "regular_scene", kind: "advertising", buyer: "home brands and interior publishers needing material-specific renovation scenes", seeds: ["compact kitchen with pale oak cabinets and a clear worktop", "dark stone island with brass-free simple hardware and daylight", "unfinished cabinet door beside labeled-by-color material swatches", "tile installer aligning a backsplash with hands visible", "small apartment kitchen using vertical storage efficiently", "sink area with water-saving fixture and natural light", "open shelf styling with everyday ceramic dishes and herbs", "renovation sample board with wood, stone and paint chips", "corner breakfast nook integrated into a narrow kitchen", "warm kitchen lighting reflected across a clean stone counter"] },
  { day: 21, name: "Accessible home details and inclusive living", mode: "regular_scene", kind: "advertising", buyer: "inclusive housing and community-service publishers seeking practical, respectful accessibility imagery", seeds: ["step-free threshold between a garden and bright living room", "easy-grip kitchen tools arranged beside an adjustable counter", "contrasting stair nosing shown in a well-lit home", "lever handle on a wide uncluttered doorway", "raised garden bed with seated gardening tools nearby", "shower bench and grab bar shown in a dry accessible bathroom", "quiet sensory reading alcove with soft lighting and low shelf", "accessible picnic table with clear knee space in a park", "open route through a home with furniture placed for circulation", "tactile wayfinding tile at a covered community entrance"] },
  { day: 22, name: "Original print-ready wall art", mode: "regular_scene", kind: "artwork", buyer: "interior stylists and print publishers needing original unframed artwork ready for reproduction", seeds: ["full-bleed tidal estuary contour study in layered blue-gray", "indigo pigment blooms on handmade paper inspired by monsoon rain", "terraced field geometry reduced to warm abstract color bands", "basalt strata ink drawing with fine irregular lines", "mangrove-root negative shapes in muted mineral colors", "woven reed rhythm abstraction with generous visual balance", "lunar clay pigment circles with subtle handmade texture", "salt-marsh aerial color field with restrained green and gold", "weathered limestone botanical imprint as a monochrome print", "coastal dune lines abstracted into a soft neutral composition"] },
  { day: 23, name: "Civic participation and community services", mode: "regular_scene", kind: "advertising", buyer: "civic organizations and public-service publishers needing neutral everyday participation visuals", seeds: ["resident placing an unmarked paper form into a plain collection box", "community meeting with neighbors listening around a circular table", "volunteer explaining a local service map with labels turned away", "public library staff helping a visitor at an information desk", "hands arranging blank resource cards for a neighborhood event", "accessible community center entrance prepared for a meeting", "people waiting calmly at a service counter from a side view", "local volunteers sorting donated supplies by category", "town-hall chairs arranged before residents arrive", "close-up of hands placing a generic suggestion card in a box"] },
  { day: 24, name: "Learning through hands-on creativity", mode: "regular_scene", kind: "advertising", buyer: "education publishers and family-learning brands needing resourceful, activity-led imagery", seeds: ["adult instructor showing a simple printmaking step to a small group", "hands building a cardboard bridge during a classroom project", "colorful paper shapes sorted for an after-school collage", "young learners' hands planting seeds in reused cups", "teacher preparing a science demonstration with safe everyday materials", "family assembling a simple wooden model at a kitchen table", "children's art supplies arranged before a workshop begins", "adult tutor helping a learner organize study notes", "library craft station with recycled paper and blunt scissors", "group project materials arranged around a blank tabletop"] },
  { day: 25, name: "Herbal wellness and garden-to-kitchen ingredients", mode: "regular_scene", kind: "advertising", buyer: "wellness and food editors needing botanical ingredients without unsupported health claims", seeds: ["fresh mint growing in a small ceramic pot beside a tea cup", "rosemary sprig and garden shears on a weathered bench", "dried calendula petals in an unmarked glass jar", "lemon balm leaves beside a plain infusion pitcher", "fresh ginger and sliced citrus on a neutral kitchen board", "sage leaves drying on a simple rack in soft daylight", "small herb garden arranged in recycled containers", "turmeric root and whole peppercorns beside a wooden spoon", "bunch of basil being rinsed at a kitchen sink", "assortment of culinary leaves organized for a recipe shoot"] },
  { day: 26, name: "Craft textiles and material-led interiors", mode: "regular_scene", kind: "advertising", buyer: "home decor publishers seeking accurately contextualized craft and tactile interior details", seeds: ["indigo resist-dyed cloth folded over a simple timber bench", "handwoven basket wall beside a natural fiber rug", "rattan chair with a locally sourced neutral textile", "bamboo bead curtain filtering afternoon light", "layered wool and jute textures beside a low reading table", "woven headboard in a linen bedroom with ample breathing room", "artisan textile swatches arranged by weave and fiber", "embroidered cushion detail in a contemporary lived-in room", "basket-making materials organized on a craft workshop table", "natural-dyed cotton hanging to dry in a bright studio"] },
  { day: 27, name: "Wildlife and biodiversity field stories", mode: "regular_scene", kind: "advertising", buyer: "conservation educators and nature publishers seeking accurate, non-staged biodiversity imagery", seeds: ["native pollinator resting on a single wildflower in a meadow", "small bird gathering nesting material on a garden branch", "frog at the edge of a clean freshwater pond", "butterfly wings shown in natural side light on a leaf", "field notebook beside binoculars at a wildlife observation point", "young mangrove seedlings along a calm tidal edge", "forest floor fungi among wet leaves after rain", "bee approaching a cluster of native blossoms", "bird footprint pattern beside a shallow shoreline", "wildlife camera setup on a tree without visible brand markings"] },
  { day: 28, name: "Movement, recovery, and inclusive fitness", mode: "regular_scene", kind: "advertising", buyer: "fitness and wellbeing publishers needing credible, varied movement and recovery imagery", seeds: ["older adult stretching beside a chair near a bright window", "runner tying shoes on a park bench before a morning jog", "yoga mat and folded towel in a modest home studio", "adaptive handcycle parked near a quiet paved trail", "friends cooling down after a neighborhood fitness class", "hands filling a reusable water bottle after exercise", "swim goggles and towel arranged beside a pool lane", "gentle balance practice beside a sturdy wall rail", "trail walking poles resting against a backpack on a bench", "community dance class warming up in a simple hall"] },
  { day: 29, name: "Architecture, stairways, and usable space", mode: "regular_scene", kind: "advertising", buyer: "architects and real-estate publishers needing distinctive, accurately composed built-environment imagery", seeds: ["repeating concrete stair geometry with a single soft shadow", "modern library atrium viewed from an upper landing", "renovated brick warehouse corridor with a clear vanishing point", "timber pavilion opening toward a planted courtyard", "compact office lobby with a distinct material transition", "sunlit arched passage in a public building without signage", "exterior facade showing passive shading and deep balconies", "quiet apartment hallway with layered natural light", "community hall roof structure seen from below", "accessible ramp integrated into a contemporary civic entrance"] },
  { day: 30, name: "Useful technology and human-computer interaction", mode: "regular_scene", kind: "advertising", buyer: "software teams and technology publishers needing human-centered, unbranded product imagery", seeds: ["hand using a smartphone to scan a generic parcel label with text blurred", "designer sketching a simple app flow on sticky notes", "remote colleague joining a video meeting in a bright home office", "hands connecting a small sensor to a houseplant moisture probe", "tablet used to review a generic inventory dashboard without readable data", "person pairing wireless headphones with a phone on a train", "customer using a self-service kiosk with screen contents abstract", "technician examining a compact wearable device on a workbench", "hands setting up a small home automation hub", "team reviewing a physical prototype beside a laptop with blank screen"] },
  { day: 31, name: "Seasonal gifting and handmade celebrations", mode: "regular_scene", kind: "advertising", buyer: "retailers and event publishers needing flexible seasonal gifting imagery without branded products", seeds: ["reusable gift wrap tied with a fresh botanical clipping", "small handmade ceramic present on folded natural-fiber cloth", "unmarked parcel beside blank greeting card and simple twine", "seasonal table setting with citrus and reusable linen napkins", "maker tying paper tags with no writing to small gift boxes", "handcrafted candle and dried flowers arranged for a winter gift guide", "colorful paper rosettes and plain gift bags before a celebration", "locally made soap bars arranged beside recycled wrapping paper", "simple celebration dessert with reusable plates and flowers", "small gift basket with regional fruit and neutral packaging"] },
] as const;

export function getBangkokDate(date: Date = new Date()): string {
  if (!Number.isFinite(date.getTime())) throw new Error("Invalid production date");
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Bangkok", year: "numeric", month: "2-digit", day: "2-digit",
  }).format(date);
}

export function getDailyCategory(date: Date = new Date()) {
  const dayOfMonth = Number(getBangkokDate(date).slice(-2));
  return MONTHLY_CATEGORIES[dayOfMonth - 1];
}

export function getDailyScheduledMode(date: Date = new Date()): GenerationMode {
  return getDailyCategory(date).mode;
}
